flake.lock
=> pkgs: weekly update (weekly-update-2024.46)

flake.nix
At last! Together with @imincik at #ZurichZHF
=> Nix search fix

flake.lock
=> pkgs: weekly update (weekly-update-2024.48)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2024.49)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2024.50)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/grass/plugins.nix, pkgs/grass/update-plugins.py, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2024.51)

flake.lock, flake.nix, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/grass/update-plugins.py, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.01)

DEVELOPMENT.md, flake.lock, flake.nix, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.03)

DEVELOPMENT.md, flake.lock, flake.nix, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix, utils/update-extra-pkgs.sh
=> pkgs: weekly update (weekly-update-2025.05)

.gitignore, DEVELOPMENT.md, flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.06)

DEVELOPMENT.md, flake.lock, flake.nix, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.07)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/grass/update-plugins.py, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.08)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.09)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.10)

DEVELOPMENT.md, flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.12)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.13)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.14)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.15)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.16)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.17)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.18)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.19)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/gdal/update-master.py, pkgs/grass/plugins-rev.nix, pkgs/grass/update-plugins-rev.py, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.21)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/qgis/qgis-ltr-plugins-list.nix, pkgs/qgis/qgis-plugins-list.nix
=> pkgs: weekly update (weekly-update-2025.22)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix
=> pkgs: weekly update (weekly-update-2025.24)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-rev.nix
=> pkgs: weekly update (weekly-update-2025.25)

flake.lock, pkgs/gdal/master-rev.nix, pkgs/grass/plugins-list.nix, pkgs/grass/plugins-rev.nix, pkgs/grass/update-plugins.py
=> pkgs: weekly update (weekly-update-2025.32)
